cc_binary(
    name = "cipher-1.1.1t",
    srcs = ["main.cpp"],
    deps = [
        "//openssl_wrapper:include",
        "//openssl_wrapper:impl-1.1.1t",
    ],
)

cc_binary(
    name = "cipher-3.3.1",
    srcs = ["main.cpp"],
    deps = [
        "//openssl_wrapper:include",
        "//openssl_wrapper:impl-3.3.1",
    ],
)
